Lesson3
MaximZagorsk/rails_begin pull request #3
Opened 2021-05-24 17:56 UTC by MaximZagorsk

2021-05-25 06:27 UTC, VidgarVii requested changes

2021-05-25 06:27 UTC, VidgarVii commented on app/models/test.rb
> +  end
запросы будет правильно решить через джойн таблиц
то как ты делаешь - это "решение в лоб"
оно работает, но оно скажем мягко "не оптимальное"

рельсы многие запросы могут сами оптимизировать в итоге и, к примеру, составить автоматически из двух запросов один, но полагаться на это не стоит
в реальной жизни такие запросы, как у тебя получились, писать не нужно

плюс мы сейчас пытаемся разобраться с тем, как работают ассоциации в рельсах, чтобы в дальнейшем было понимание того "что же они делают" и "как это работает", так вот рельсы точно не пишут такие запросы, конечно же все оптимизировано
посмотри предыдущее задание - там были (в части по скуль запросам) селекты с джойнами таблиц

здесь нужно в обоих методах решить все с помощью `joins` и `where` (в одно обращение к базе, один запрос)
пострайся разобраться - это важно и полезно

2021-05-25 06:27 UTC, VidgarVii commented on db/seeds.rb
> +answer_qjsb = Answer.create!(title: "No", correct: false, question_id: question_javascriptbegin.id)
вместо сотен переменных можно было использовать коллекцию. Посмотри коментарий выше как используется movies

2021-05-25 11:42 UTC, MaximZagorsk commented on app/models/test.rb
> +  end
Понял, почитаю документацию и напишу

2021-05-25 11:43 UTC, MaximZagorsk commented on db/seeds.rb
> +answer_qjsb = Answer.create!(title: "No", correct: false, question_id: question_javascriptbegin.id)
Это там где хеши получается?

2021-05-27 17:47 UTC, VidgarVii commented on app/models/test.rb
> +    Test.joins('INNER JOIN categories ON categories.id = tests.category_id')
inner писать не обязательно. Он имеется ввиду по умолчанию

2021-05-27 17:47 UTC, VidgarVii commented on app/models/test.rb
> +        .order('id DESC')
.order(title: :desc)

2021-05-27 17:47 UTC, VidgarVii commented on db/seeds.rb
> +answer_qjsb = Answer.create!(title: "No", correct: false, question_id: question_javascriptbegin.id)
да

2021-05-27 17:48 UTC, VidgarVii requested changes

2021-05-27 17:48 UTC, VidgarVii commented on db/seeds.rb
> +result_ivan = Result.create!(test_id: test_rails.id, user_id: user_Ivan.id, ending: true)
не исправил

2021-05-28 08:24 UTC, MaximZagorsk commented on app/models/test.rb
> +        .order('id DESC')
Понял, по полю названия

2021-05-28 14:52 UTC, VidgarVii requested changes

2021-05-28 14:52 UTC, VidgarVii commented on db/seeds.rb
> +user_Jack = User.create!(username: 'Jack', password: 214_567)
1 не исправил прошлые замечания
2 не надо определять 1кк переменных. Это забивает оперативную память и нагружает сборщик мусора

Используй пример из комментария выше. Тебе рельса уже говорит как надо создать сиды. Только используй create! вместо create
```
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.creae(name: 'Luke', movie: movies.first)
```

2021-05-31 12:12 UTC, merged